
sequenceDiagram
    participant Client
    participant Server

    %% Initialisation
    Note over Client,Server: DELETE non_existing_file.txt
    Client->>Server: Establish connection
    Server<<-->>Client: Connection established
    Client->>Server: DELETE non_existing_file.txt
    Server--)Client: ENOENT
    Client->>Server: Close connection
    Server->>Server: Close connection
    Server<<-->>Client: Connection closed
