sequenceDiagram
    participant Client
    participant Server

    %% Initialisation
    Note over Client,Server: GET file.txt
    Client->>Server: Establish connection
    Server<<-->>Client: Connection established
    Client->>Server: GET MYFILE.TXT
    Server--)Client: 0
    Server--)Client: 1024
    Server--)Client: Your content
    Client->>Server: Close connection
    Server->>Server: Close connection
    Server<<-->>Client: Connection closed

