sequenceDiagram
    participant Client
    participant Server

    %% Initialisation
    Note over Client,Server: LIST myfile
    Client->>Server: Establish connection
    Server<<-->>Client: Connection established
    Client->>Server: LIST myfile
    Server--)Client: ENOTDIR
    Client->>Server: Close connection
    Server->>Server: Close connection
    Server<<-->>Client: Connection closed
