sequenceDiagram
    participant Client
    participant Server

    Note over Client,Server: LIST my_dir
    Client->>Server: Establish connection
    Server<<-->>Client: Connection established
    Client->>Server: List content of my_dir
    Server--)Client: Send request result
    Server--)Client: Send content of directory
    Server->>Server: Close socket
    Server<<-->>Client: Connection closed
