sequenceDiagram
    participant Client
    participant Server

    Note over Client,Server: PUT other_file.txt
    Client->>Server: Establish connection
    Server<<-->>Client: Connection established
    Client->>Server: Annonce that wants to create a file
    Client->>Server: Send the content of the file
    Server--)Client: Send request result
    Server->>Server: Close socket
    Server<<-->>Client: Connection closed

