sequenceDiagram
    participant Client
    participant Server

    %% Initialisation
    Note over Client,Server: PUT myfile.txt 1024
    Client->>Server: Establish connection
    Server<<-->>Client: Connection established
    Client->>Server: PUT myfile 1024
    Client->>Server: Fle content
    Server--)Client: 0
    Client->>Server: Close connection
    Server->>Server: Close connection
    Server<<-->>Client: Connection closed
